# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cbb2dc08c4c45694d8e362d24478c0ea5f8a1e9f2cd1be9afc77f06b6a6b97d077ff622460113a6e8adf872b3148001833bbdebcee4a9e86c79f329805791cf6

test:
  secret_key_base: 52699e6d31a85abce431f315c26ae7e53fababca08f8708e098d9657a5ef3eb00430afd3fa4e6fcedfeff19e65d679a52c14e5b30b4ef47028448dd9c3de230d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
